FROM koenkk/zigbee2mqtt:latest as base

SHELL ["/bin/ash", "-o", "pipefail", "-c"]

# Install socat
RUN \
    apk add --no-cache --virtual .build-dependencies \
        curl \
        tar \
    \
    && apk add --no-cache \
        socat \
        bash  \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz" \
        | tar zxvf - -C / \
    \
    && mkdir -p /etc/fix-attrs.d \
    && mkdir -p /etc/services.d \
    \
    && rm -fr \
        /tmp/* 
        
# Entrypoint & CMD
ENTRYPOINT ["/init"]

# Copy root filesystem
COPY rootfs /


