#!/usr/bin/with-contenv bash

if [[ -z "${SOCAT_ZIGBEE_TYPE}" ]]; then
  SOCAT_ZIGBEE_TYPE="tcp"
fi
if [[ -z "${SOCAT_ZIGBEE_LOG}" ]]; then
  SOCAT_ZIGBEE_LOG="-lf \"$SOCAT_ZIGBEE_LOG\""
fi
if [[ -z "${SOCAT_ZIGBEE_LINK}" ]]; then
  SOCAT_ZIGBEE_LINK="/dev/zigbee"
fi

PARAMS="$INT_SOCAT_LOG -d pty,b115200,raw,echo=0,link=$SOCAT_ZIGBEE_LINK $SOCAT_ZIGBEE_TYPE:$SOCAT_ZIGBEE_HOST:$SOCAT_ZIGBEE_PORT"

######################################################

# CMD=$1

if [[ -z "${CONFIG_LOG_TARGET}" ]]; then
  LOG_FILE="/dev/null"
else
  LOG_FILE="${CONFIG_LOG_TARGET}"
fi
echo "starting... socat $PARAMS"
exec socat $PARAMS &